name: Generate and Publish Plot

on:
  push:
    branches:
      - main
  schedule:
    - cron:  '0 0 1 * *' # Daily at midnight

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install numpy matplotlib
    
    - name: Generate plot
      run: python Exotics_plot.py
    
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./ # Adjust this to where your plot.png is generated
